services:
  backend:
    build: .
    container_name: task_manager_backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgresql
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@postgresql:5432/taskmanager
    
  redis:
    image: "redis:alpine"
    container_name: task_manager_redis
    ports:
      - "6379:6379"

  postgresql:
    image: "postgres:alpine"
    container_name: task_manager_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taskmanager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
